development:
  bucket: DemoLessonVideo
  access_key_id: AKIAJIHMXETPW2S76K4A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
    
test:
  bucket: DemoLessonVideo
  access_key_id: AKIAJIHMXETPW2S76K4A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
  
production:
  bucket: DemoLessonVideo
  access_key_id: AKIAJIHMXETPW2S76K4A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
