---
development:
  cloudsponge:
    domainKey: "8C7MFY8C7PDGQPDBNY3Y"
    domainPassword: "qBllL4lCeVqJoEGl"
production:
  cloudsponge:
    # DemoLesson.com
    domainKey: "3Z4S85SUET5Z5AJEEERR"
    domainPassword: "422NkRAnq4Y9EGn4"
    # Tioki.com
    #domainKey: "HKY55PWXKBCMNTYWSAV7"
    #domainPassword: "3QglPk583veJMRNo"